#!/bin/bash -eux

git rev-parse --git-dir &> /dev/null
if [[ $# -eq 0 ]]; then
  echo 'echo hello, world' > hello
  chmod +x hello
  diff - <(./hello) <<< "hello, world"
  git add hello
  git commit -m"the canonical program" hello
else
  for i in "$@"; do
    [ ${i:0:1} != '/' ] # relative paths & real files only
    name="$PWD/$i"
    rm -rf $name
    if [[ ${name: -1:1} = '/' ]]; then
      install -d $name
      > $name/.gitkeep
    else
      install -d $(dirname $name)
      echo "file $i" > $name
    fi
    git add "$name"
  done
  git commit -m"create file(s) $@" "$@"
fi
