#!/bin/bash

die() { echo "$@" >&2; exit -1; }
usage="usage: $0 [layer-depth]"
[[ $1 == --help ]] && die $usage

git rev-list --ancestry-path $(git-first)..master --topo-order --reverse | sed 's/$/^/' | awk "(NR-1)%${1:-1}==0" |
  while read i; do
    git rev-parse $i
  done
