#!/bin/bash

die() { echo "$@" >&2; exit 1; }
usage="usage:$0 [--help] <filename>"

[[ $1 == --help ]] && die $usage

sha1=$(git log --follow --oneline master -- $1 | tail -1 | cut -f1 -d' ') # SHA1 of first commit with file $1
if [ "${sha1}" ]; then
  echo $sha1
else
  false # fail silently if there is none
fi
