#!/bin/bash -eu

exec >/dev/null

# create the initial repo
subcmd=${0##*-}
git scratch ${1:-$subcmd}
cd $_
git addfile

# branch here
git checkout -qb davidian

# radical change to davidian
git rm hello
git commit -m'unfriendly' hello
git addfile buzz-off

# benign changes to master
git checkout -q -
echo echo happy birthday, evi > hello
./hello
git commit -m'7 June 1940' hello

# prep for rebase
git checkout -q -
