#!/bin/bash -eu

# create a pair of repos
for i in sub scratch;
do
  git scratch -R $i
done

# make 'sub' a submodule of 'scratch'
cd scratch
git submodule add ssh://localhost/tmp/sub.git sub
git commit -am'a submodule'
git push
cd -

# now clean up, and get a fresh copy
rm -rf sub scratch
git clone --recursive ssh://localhost/tmp/scratch.git

exit 0

# check out the master branch
cd top
git submodule foreach git checkout master

# add a new file to the module and submodule
git addfile top.new
git -C sub addfile sub.new

# push
git push --recurse-submodules=on-demand

exit 0
