#!/bin/bash -e
# Aristotle Pagaltzis's 
# https://stackoverflow.com/a/38083908 piped through sort
# optionally shows incoming objects

shopt -s nullglob extglob

list_objects() {
	# packed objects
	for p in pack/pack-*([0-9a-f]).idx ; do
	    git show-index < $p | cut -f 2 -d ' '
	done

	# loose objects
	for o in [0-9a-f][0-9a-f]/*([0-9a-f]) ; do
	    echo ${o/\/}
	done
}


cd $(git rev-parse --git-dir)
objects="$PWD/objects"

cd $objects
list_objects

# incoming objects
if [[ "${1:-}" = "-i" ]]; then
	for i in incoming*; do
	    [[ -d $i ]] && (cd $i; list_objects)
	done
fi
