#!/bin/bash -eu

bigfiles="${1:-*.big}"

git scratch; cd $_
git lfs track "$bigfiles"
git add .gitattributes
git commit -am"files with extension '$bigfiles' are large"
git addfile hello hello.big
hub create
if git fetch && git branch -a | grep origin; then
  git pull origin master
fi
git push -u origin master
git lfs ls-files
