#!/bin/bash -eu

week_nums="$@"
dig=$PWD/source.git
git -C source remote set-url dig $dig            # use it as the remote

# tag the points we want to measure
set_pitons() {
  cd source
    for i in $week_nums; do
      piton_sha1=$(git log -1 --before="$i weeks ago" | perl -lane 'print if s/^commit //')
      [[ "$piton_sha1" ]] && git tag -f piton/$i $piton_sha1
    done
  cd ~-
}

# clean out the old dig
cleanup() {
  set +e
  rm -rf $dig
  set -e
} 2>/dev/null
trap "cleanup" EXIT

# report whatever measure we're using
measure() {
  du -sh $1/objects
}

set_pitons

# now for the real work
for i in $week_nums; do
  cleanup
  git init --quiet --bare $dig                         # make a new dig
  git -C source push -q dig piton/$i:master    # make a version of the raw repo up to the piton
  printf "$i weeks ago: "                      # report its size
  measure $dig
done
