#!/bin/bash -eu

die() { echo "$@" >&2; exit 1; }
usage="usage: $0 [-nbct]"

# two special cases
if (( $# == 0 )); then
  git cat-file --batch-check --batch-all-objects # just print
  exit 0
elif (( $# == 1 )); then
  [[ $1 == -n ]] && set -- -nbct	# count all objects
fi

: ${blobs:=} ${commits:=} ${counts:=} ${trees:=}	# defaults

while getopts bcnt opt; do
  case $opt in
    b) blobs=1    ;;
    c) commits=1  ;;
    h) die $usage ;;
    n) counts=1   ;;
    t) trees=1    ;;
  esac
done

tmp=/tmp/$$
git cat-file --batch-check --batch-all-objects > $tmp
trap 'rm $tmp' EXIT

if [[ "$counts" ]]; then
  [ "$commits" ] && printf "%8s" $(grep -c commit $tmp)
  [ "$trees" ] && printf "%8s" $(grep -c tree $tmp)
  [ "$blobs" ] && printf "%8s" $(grep -c blob $tmp)
  echo
  exit 0
fi

regex=""
[ "$commits" ] && regex+="|commit"
[ "$trees" ] && regex+="|tree"
[ "$blobs" ] && regex+="|blob"
egrep "${regex:1}" $tmp
