#!/bin/bash -eu

bigfiles="${1:-*.big}"

git scratch; cd $_
git lfs track "$bigfiles"
git add .gitattributes
git commit -am"files with extension '$bigfiles' are large"
hub create
git addfile hello hello.big
git push -u origin master
git lfs ls-files
